const mongoose = require("mongoose");

const Calculation = new mongoose.Schema(
  {
    company: { type: String, required: true },
    comment: { type: String },
    date: { type: Date, required: true },
    type: {
      type: String,
      enum: ["daily", "weekly", "monthly", "quarterly", "half-yearly"],
      default: "daily",
      required: true,
    },
    ph: { type: Number, required: true },
    pl: { type: Number, required: true },
    pc: { type: Number, required: true },
    pph: { type: Number, required: true },
    ppl: { type: Number, required: true },
    ppc: { type: Number, required: true },
    tst00: { type: Number, required: true },
    tst01: { type: Number, required: true },
    tst02: { type: Number },
    tst10: { type: Number, required: true },
    tst11: { type: Number },
    rctv: { type: Number, required: true },
    fctv: { type: Number, required: true },
    rcnz1: { type: Number, required: true },
    rcnz2: { type: Number, required: true },
    rcnz3: { type: Number, required: true },
    rcmz1: { type: Number, required: true },
    rcmz2: { type: Number, required: true },
    rcwz1: { type: Number, required: true },
    rcwz2: { type: Number, required: true },
    rcwz3: { type: Number, required: true },
    rcnz1_us: { type: Number, required: true },
    rcnz1_ls: { type: Number, required: true },
    rcnz2_us: { type: Number, required: true },
    rcnz2_ls: { type: Number, required: true },
    rcnz3_us: { type: Number, required: true },
    rcnz3_ls: { type: Number, required: true },
    rcmz1_us: { type: Number, required: true },
    rcmz1_ls: { type: Number, required: true },
    rcmz2_us: { type: Number, required: true },
    rcmz2_ls: { type: Number, required: true },
    rcwz1_us: { type: Number, required: true },
    rcwz1_ls: { type: Number, required: true },
    rcwz2_us: { type: Number, required: true },
    rcwz2_ls: { type: Number, required: true },
    rcwz3_us: { type: Number, required: true },
    rcwz3_ls: { type: Number, required: true },
    fcnz1: { type: Number, required: true },
    fcnz2: { type: Number, required: true },
    fcnz3: { type: Number, required: true },
    fcmz1: { type: Number, required: true },
    fcmz2: { type: Number, required: true },
    fcwz1: { type: Number, required: true },
    fcwz2: { type: Number, required: true },
    fcwz3: { type: Number, required: true },
    fcnz1_us: { type: Number, required: true },
    fcnz1_ls: { type: Number, required: true },
    fcnz2_us: { type: Number, required: true },
    fcnz2_ls: { type: Number, required: true },
    fcnz3_us: { type: Number, required: true },
    fcnz3_ls: { type: Number, required: true },
    fcmz1_us: { type: Number, required: true },
    fcmz1_ls: { type: Number, required: true },
    fcmz2_us: { type: Number, required: true },
    fcmz2_ls: { type: Number, required: true },
    fcwz1_us: { type: Number, required: true },
    fcwz1_ls: { type: Number, required: true },
    fcwz2_us: { type: Number, required: true },
    fcwz2_ls: { type: Number, required: true },
    fcwz3_us: { type: Number, required: true },
    fcwz3_ls: { type: Number, required: true },
  },
  { collection: "calculation" },
);

const CalculationModel = mongoose.model("Calculation", Calculation);

module.exports = { CalculationModel };
